### ISSUE TITLE
How might we create a product category "landing" page?

### ISSUE THREAD

**Issue by bnaolu** [Bixal/med-supply-cat#14]
When transitioning between selecting the category and the product detail/description pages, how might the product category landing page look like?

**Comment by bnaolu** [comment]
@pglevy @kbchumley 

Here are a few options for the product category list. Don't mind the messy code right now.
Would love to hear your thoughts and opinions:
 
[Option 1](https://codepen.io/bnaolu/pen/XWMdWrJ?editors=1000) - follows the "collection" component
- Going along with the "add to list" concept, not sure how I feel about the buttons here; possible to swap this out with something else.

[Option 2](https://codepen.io/bnaolu/pen/eYvdNyr?editors=1000) - follows the "card" component
- I added an "add" icon on the bottom right of the cards instead of the button, which is pretty bulky and doesn't look right with the tags on this page.

[Option 3](https://codepen.io/bnaolu/pen/MWppaQV?editors=1000) - follows the "list" component
- Nothing too crazy here; just a list view of the products without any distractions. Could possibly add margin spacing and other elements later.

**Comment by pglevy** [comment]
Hey Brianna, Thanks for exploring these options! I think options 1 and 2 are promising. Leaning toward the collection component, but the combination of the font weight, tags, and primary button make it feel a bit too busy and heavy. On the cards, the add button a bit subtle as just an icon. And the list-only approach of option 3 doesn't seem very scannable. 

I did a [fork of your collection pen](https://codepen.io/pglevy/pen/wvJJXrZ?editors=1000) and start playing with some styling and added the media thumbnails. See what you think of some of those tweaks and we can sync up on it later.

**Comment by bnaolu** [comment]
Collection [Option 1](https://codepen.io/bnaolu/pen/XWMdWrJ?editors=1000) -
- Added additional meta-data
- Fixed up some of the spacing issues with the product name
- Used the link instead of button for "add to list" feature; shifted more right-aligned

Collection [Option 2 ](https://codepen.io/bnaolu/pen/QWpvJbw?editors=1000)-
- Added additional meta-data 
- Fixed up some of the spacing issues with the product name
- Kept the button but shifted more right-aligned

Card [Option 3](https://codepen.io/bnaolu/pen/eYvdNyr?editors=1000) - 
- Made things a bit cleaner 
- Added images to the cards

**Comment by pglevy** [comment]
These look great. I think option 2 is a good balance of text, image, and CTA. I'll work on a layout based on that one.
